services:
  - type: web
    name: my-app
    env: node
    build:
      command: "npm run build"
    proxy:
      /images:
        target: [https://image-backend-zvjc.onrender.com](https://image-backend-zvjc.onrender.com)
        changeOrigin: true
        pathRewrite: "^/images"
